- name: 'bump:major'
  color: '1b9e77'
  description: '[Release] Flag this PR as a major version release.'
- name: 'bump:minor'
  color: 'd95f02'
  description: '[Release] Flag this PR as a minor version release.'
- name: 'bump:patch)'
  color: '7570b3'
  description: "[Release] Flag this PR as a patch for release.'
