name: Feature Request
description: Request a new feature or an enhancement to an existing feature.
title: "[Feature]: "
labels: ["enhancement"]
projects: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Provide a clear and concise description of what the problem is, e.g. Our users are now requiring the ability to ... OR There is currently not a way for me as a user to ... .
      placeholder: What problem are you trying to solve with this feature? What is the benefit for the user?
      value: "Gee Brain, what are we gonna do tonight?"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: Include a clear and concise description of what you want to happen, e.g. This will benefit users because ... . Include any code or visual designs - if applicable - that could help illustrate the idea
      placeholder: Tell us what you think we should do
      value: "The same thing we do every night, try to take over the world!"
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Considerd Alternatives
      description: A clear and concise description of any alternative solutions, ideas, code or design you've considered for this idea and why they were not selected.
      placeholder: Tell us what you think we shouldn't do
      value: "The irony of it all, Pinky. Years of trying to take over the world, and all I had to do was say 'moo'."
