name: Bug Report
description: File a bug report.
labels: ["bug"]
projects: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        ⛔ Note: Before filling out this form, please search to see if an issue is already open or previously closed for the bug you have encountered to prevent duplication. ⛔
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see! And add screenshots!
      value: "A bug happened!"
    validations:
      required: true
  - type: checkboxes
    id: test
    attributes:
      label: Regression Test
      description: Is a regression test required for this bug fix?
      options:
        - label: Of course it is!
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running? Please include the branch name and commit hash if possible.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
